//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetPark.FrontEnd.Left {
    
    
    public partial class Left {
        
        /// <summary>
        /// Categories1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InternetPark.FrontEnd.Left.Module.Categories Categories1;
        
        /// <summary>
        /// Books_Hightlight1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::InternetPark.FrontEnd.Left.Module.Books_Hightlight Books_Hightlight1;
    }
}
